// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CurrencyRates.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PobieranieDziennychKursowWalutFeature : object, Xunit.IClassFixture<PobieranieDziennychKursowWalutFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DzienneKursyWalut.feature"
#line hidden
        
        public PobieranieDziennychKursowWalutFeature(PobieranieDziennychKursowWalutFeature.FixtureData fixtureData, CurrencyRates_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pl"), "Features", "Pobieranie dziennych kursów walut", "    Jako użytkownik systemu\r\n    Chcę mieć dostęp do historycznych kursów walut d" +
                    "la konkretnego dnia\r\n    Aby móc sprawdzać wartości walut w wybranym dniu", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Pobieranie kursu waluty dla konkretnego dnia")]
        [Xunit.TraitAttribute("FeatureTitle", "Pobieranie dziennych kursów walut")]
        [Xunit.TraitAttribute("Description", "Pobieranie kursu waluty dla konkretnego dnia")]
        public void PobieranieKursuWalutyDlaKonkretnegoDnia()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pobieranie kursu waluty dla konkretnego dnia", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given("wybraną walutę \"USD\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mając ");
#line hidden
#line 9
    testRunner.And("wybraną datę \"2022-01-31\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
#line 10
    testRunner.When("sprawdzam historyczny kurs dzienny", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Gdy ");
#line hidden
#line 11
    testRunner.Then("system zwraca poprawną odpowiedź", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line hidden
#line 12
    testRunner.And("odpowiedź zawiera prawidłowe dane kursu historycznego", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
#line 13
    testRunner.And("wartość kursu jest większa od 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Próba pobrania kursu dla nieprawidłowej daty")]
        [Xunit.TraitAttribute("FeatureTitle", "Pobieranie dziennych kursów walut")]
        [Xunit.TraitAttribute("Description", "Próba pobrania kursu dla nieprawidłowej daty")]
        public void ProbaPobraniaKursuDlaNieprawidlowejDaty()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Próba pobrania kursu dla nieprawidłowej daty", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 16
    testRunner.Given("wybraną walutę \"USD\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mając ");
#line hidden
#line 17
    testRunner.And("wybraną datę \"2099-99-99\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
#line 18
    testRunner.When("sprawdzam historyczny kurs dzienny", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Gdy ");
#line hidden
#line 19
    testRunner.Then("system zwraca błąd nieprawidłowego żądania", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PobieranieDziennychKursowWalutFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PobieranieDziennychKursowWalutFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
