// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CurrencyRates.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PobieranieKwartalnychKursowWalutFeature : object, Xunit.IClassFixture<PobieranieKwartalnychKursowWalutFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "KwartalneKursyWalut.feature"
#line hidden
        
        public PobieranieKwartalnychKursowWalutFeature(PobieranieKwartalnychKursowWalutFeature.FixtureData fixtureData, CurrencyRates_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pl"), "Features", "Pobieranie kwartalnych kursów walut", "    Jako użytkownik systemu\r\n    Chcę mieć dostęp do historycznych kursów walut d" +
                    "la wybranego kwartału\r\n    Aby móc analizować zmiany wartości walut w okresie kw" +
                    "artalnym", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Pobieranie kursów waluty dla konkretnego kwartału")]
        [Xunit.TraitAttribute("FeatureTitle", "Pobieranie kwartalnych kursów walut")]
        [Xunit.TraitAttribute("Description", "Pobieranie kursów waluty dla konkretnego kwartału")]
        public void PobieranieKursowWalutyDlaKonkretnegoKwartalu()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pobieranie kursów waluty dla konkretnego kwartału", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given("zdefiniowaną walutę \"USD\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mając ");
#line hidden
#line 9
    testRunner.And("zdefiniowany rok \"2024\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
#line 10
    testRunner.And("zdefiniowany kwartał \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
#line 11
    testRunner.When("pobieram kursy kwartalne", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Gdy ");
#line hidden
#line 12
    testRunner.Then("odpowiedź z kursami kwartalnymi jest udana", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line hidden
#line 13
    testRunner.And("lista kursów kwartalnych jest prawidłowa", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
#line 14
    testRunner.And("wszystkie kursy kwartalne są większe od 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Próba pobrania kursów dla nieprawidłowego kwartału")]
        [Xunit.TraitAttribute("FeatureTitle", "Pobieranie kwartalnych kursów walut")]
        [Xunit.TraitAttribute("Description", "Próba pobrania kursów dla nieprawidłowego kwartału")]
        public void ProbaPobraniaKursowDlaNieprawidlowegoKwartalu()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Próba pobrania kursów dla nieprawidłowego kwartału", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 17
    testRunner.Given("zdefiniowaną walutę \"USD\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mając ");
#line hidden
#line 18
    testRunner.And("zdefiniowany rok \"2024\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
#line 19
    testRunner.And("zdefiniowany kwartał \"5\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
#line 20
    testRunner.When("pobieram kursy kwartalne", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Gdy ");
#line hidden
#line 21
    testRunner.Then("system zwraca błąd nieprawidłowego kwartału", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PobieranieKwartalnychKursowWalutFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PobieranieKwartalnychKursowWalutFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
