// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CurrencyRates.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PobieranieAktualnegoKursuWalutyFeature : object, Xunit.IClassFixture<PobieranieAktualnegoKursuWalutyFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PobieranieKursowWalut.feature"
#line hidden
        
        public PobieranieAktualnegoKursuWalutyFeature(PobieranieAktualnegoKursuWalutyFeature.FixtureData fixtureData, CurrencyRates_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pl"), "Features", "Pobieranie aktualnego kursu waluty", "    Jako użytkownik systemu\r\n    Chcę mieć możliwość sprawdzenia aktualnego kursu" +
                    " waluty\r\n    Aby móc śledzić bieżące kursy walut", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Pobieranie aktualnego kursu dla prawidłowej waluty")]
        [Xunit.TraitAttribute("FeatureTitle", "Pobieranie aktualnego kursu waluty")]
        [Xunit.TraitAttribute("Description", "Pobieranie aktualnego kursu dla prawidłowej waluty")]
        public void PobieranieAktualnegoKursuDlaPrawidlowejWaluty()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pobieranie aktualnego kursu dla prawidłowej waluty", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given("kod waluty \"USD\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mając ");
#line hidden
#line 9
    testRunner.When("wysyłam zapytanie o aktualny kurs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Gdy ");
#line hidden
#line 10
    testRunner.Then("odpowiedź powinna być udana", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line hidden
#line 11
    testRunner.And("odpowiedź powinna zawierać prawidłowe dane kursu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Pobieranie aktualnego kursu dla nieprawidłowej waluty")]
        [Xunit.TraitAttribute("FeatureTitle", "Pobieranie aktualnego kursu waluty")]
        [Xunit.TraitAttribute("Description", "Pobieranie aktualnego kursu dla nieprawidłowej waluty")]
        public void PobieranieAktualnegoKursuDlaNieprawidlowejWaluty()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pobieranie aktualnego kursu dla nieprawidłowej waluty", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 14
    testRunner.Given("kod waluty \"XXX\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mając ");
#line hidden
#line 15
    testRunner.When("wysyłam zapytanie o aktualny kurs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Gdy ");
#line hidden
#line 16
    testRunner.Then("system zwraca błąd serwera", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PobieranieAktualnegoKursuWalutyFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PobieranieAktualnegoKursuWalutyFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
