// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CurrencyRates.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class OperacjeNaBazieDanychDlaKursowWalutFeature : object, Xunit.IClassFixture<OperacjeNaBazieDanychDlaKursowWalutFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "WarstwaBazodanowaTests.feature"
#line hidden
        
        public OperacjeNaBazieDanychDlaKursowWalutFeature(OperacjeNaBazieDanychDlaKursowWalutFeature.FixtureData fixtureData, CurrencyRates_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pl"), "Features", "Operacje na bazie danych dla kursów walut", "    Jako użytkownik systemu\r\n    Chcę prawidłowo zapisywać i odczytywać kursy wal" +
                    "ut z bazy danych\r\n    Aby zapewnić spójność i dostępność danych historycznych", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Zapisywanie nowego kursu waluty w bazie danych")]
        [Xunit.TraitAttribute("FeatureTitle", "Operacje na bazie danych dla kursów walut")]
        [Xunit.TraitAttribute("Description", "Zapisywanie nowego kursu waluty w bazie danych")]
        public void ZapisywanieNowegoKursuWalutyWBazieDanych()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Zapisywanie nowego kursu waluty w bazie danych", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given("nowy kurs waluty \"NOK\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mając ");
#line hidden
#line 9
    testRunner.And("wartość kursu 4.0124", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
#line 10
    testRunner.And("datę kursu \"2024-01-24\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
#line 11
    testRunner.When("zapisuję kurs w bazie danych", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Gdy ");
#line hidden
#line 12
    testRunner.Then("kurs zostaje poprawnie zapisany", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line hidden
#line 13
    testRunner.And("mogę odczytać ten sam kurs z bazy", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Próba zapisania istniejącego kursu waluty")]
        [Xunit.TraitAttribute("FeatureTitle", "Operacje na bazie danych dla kursów walut")]
        [Xunit.TraitAttribute("Description", "Próba zapisania istniejącego kursu waluty")]
        public void ProbaZapisaniaIstniejacegoKursuWaluty()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Próba zapisania istniejącego kursu waluty", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 16
    testRunner.Given("istniejący kurs waluty \"EUR\" z dnia \"2025-01-23\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mając ");
#line hidden
#line 17
    testRunner.When("próbuję zapisać ten sam kurs ponownie", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Gdy ");
#line hidden
#line 18
    testRunner.Then("operacja kończy się niepowodzeniem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                OperacjeNaBazieDanychDlaKursowWalutFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                OperacjeNaBazieDanychDlaKursowWalutFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
